buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
}
apply plugin: 'net.minecraftforge.gradle'

version = '1.3.0+1.18.2'
group = 'net.vonix'
archivesBaseName = 'xpskilltree-forge-1.18.2'
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.2'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods { xpskilltree { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods { xpskilltree { source sourceSets.main } }
        }
    }
}

repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.18.2-40.2.0' }

jar {
    manifest {
        attributes([
            'Specification-Title': 'XP Skill Tree',
            'Specification-Vendor': 'Vonix.Network',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Vonix.Network'
        ])
    }
}

publishing { publications { mavenJava(MavenPublication) { artifact jar } } }
